{{- if .Values.imageVectorOverwrite }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gardener-extension-{{ .Values.serviceName }}-imagevector-overwrite
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
data:
  images_overwrite.yaml: |
{{ .Values.imageVectorOverwrite | indent 4 }}
{{- end }} 