apiVersion: v1
kind: Secret
metadata:
  name: falco-certs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: falco
    helm.sh/chart: {{ include "falco.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- $key := .Values.falcocerts.client_key }}
  client.key: {{ $key | b64enc | quote }}
  {{- $crt := .Values.falcocerts.client_crt }}
  client.crt: {{ $crt | b64enc | quote }}
  {{- $client_ca := .Values.falcocerts.client_ca_crt }}
  client.ca.crt: {{ $client_ca | b64enc | quote }}
  {{- $server_ca := .Values.falcocerts.server_ca_crt }}
  server.ca.crt: {{ $server_ca | b64enc | quote }}
